# Generated by Django 5.0.6 on 2026-05-21 09:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Очікує оплати"),
                            ("paid", "Оплачено"),
                            ("shipped", "Відправлено"),
                            ("delivered", "Доставлено"),
                            ("cancelled", "Скасовано"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                ("full_name", models.CharField(max_length=120, verbose_name="ПІБ")),
                ("phone", models.CharField(max_length=32, verbose_name="Телефон")),
                ("address", models.CharField(max_length=255, verbose_name="Адреса доставки")),
                ("comment", models.TextField(blank=True, verbose_name="Коментар")),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12, verbose_name="Сума"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Створено")),
                ("paid_at", models.DateTimeField(blank=True, null=True, verbose_name="Оплачено")),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Покупець",
                    ),
                ),
            ],
            options={
                "verbose_name": "Замовлення",
                "verbose_name_plural": "Замовлення",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=160, verbose_name="Назва на момент замовлення"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Ціна на момент замовлення"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Кількість")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиція замовлення",
                "verbose_name_plural": "Позиції замовлення",
            },
        ),
    ]
