# Generated by Django 5.0.6 on 2026-05-21 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Створено")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Оновлено")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Користувач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сесія чату",
                "verbose_name_plural": "Сесії чату",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "Користувач"), ("assistant", "Асистент")],
                        max_length=16,
                        verbose_name="Роль",
                    ),
                ),
                ("content", models.TextField(verbose_name="Текст")),
                ("is_pending", models.BooleanField(default=False, verbose_name="Очікує відповіді")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Створено")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="support.chatsession",
                        verbose_name="Сесія",
                    ),
                ),
            ],
            options={
                "verbose_name": "Повідомлення",
                "verbose_name_plural": "Повідомлення",
                "ordering": ["created_at"],
            },
        ),
    ]
